DROP TABLE IF EXISTS "users" CASCADE;

DROP TABLE IF EXISTS "sessions" CASCADE;

DROP TABLE IF EXISTS "roles" CASCADE;

DROP TABLE IF EXISTS "posts" CASCADE;

DROP TABLE IF EXISTS "categories" CASCADE;