// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID           int64     `json:"id"`
	CategoryName string    `json:"category_name"`
	Description  string    `json:"description"`
	CreatedAt    time.Time `json:"created_at"`
}

type Post struct {
	ID         int64     `json:"id"`
	Username   string    `json:"username"`
	Tag        string    `json:"tag"`
	Title      string    `json:"title"`
	ImageUrl   string    `json:"image_url"`
	Content    string    `json:"content"`
	CategoryID string    `json:"category_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Role struct {
	ID        int64     `json:"id"`
	RoleName  string    `json:"role_name"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	Email          string    `json:"email"`
	RoleID         int64     `json:"role_id"`
	UpdatedAt      time.Time `json:"updated_at"`
	CreatedAt      time.Time `json:"created_at"`
}
