// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: post.sql

package db

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
  username,
  title,
  image_url,
  content,
  category_id
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, username, title, image_url, content, category_id, created_at
`

type CreatePostParams struct {
	Username   string `json:"username"`
	Title      string `json:"title"`
	ImageUrl   string `json:"image_url"`
	Content    string `json:"content"`
	CategoryID int64  `json:"category_id"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.Username,
		arg.Title,
		arg.ImageUrl,
		arg.Content,
		arg.CategoryID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Title,
		&i.ImageUrl,
		&i.Content,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, username, title, image_url, content, category_id, created_at FROM posts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Title,
		&i.ImageUrl,
		&i.Content,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, username, title, image_url, content, category_id, created_at FROM posts
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Title,
			&i.ImageUrl,
			&i.Content,
			&i.CategoryID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET 
  title = $2,
  image_url = $3,
  content = $4,
  category_id = $5
WHERE id = $1
RETURNING id, username, title, image_url, content, category_id, created_at
`

type UpdatePostParams struct {
	ID         int64  `json:"id"`
	Title      string `json:"title"`
	ImageUrl   string `json:"image_url"`
	Content    string `json:"content"`
	CategoryID int64  `json:"category_id"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.ImageUrl,
		arg.Content,
		arg.CategoryID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Title,
		&i.ImageUrl,
		&i.Content,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}
