// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: post.sql

package db

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
  username,
  tag,
  title,
  image_url,
  content,
  category_id
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, username, tag, title, image_url, content, category_id, created_at
`

type CreatePostParams struct {
	Username   string `json:"username"`
	Tag        string `json:"tag"`
	Title      string `json:"title"`
	ImageUrl   string `json:"image_url"`
	Content    string `json:"content"`
	CategoryID string `json:"category_id"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.Username,
		arg.Tag,
		arg.Title,
		arg.ImageUrl,
		arg.Content,
		arg.CategoryID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Tag,
		&i.Title,
		&i.ImageUrl,
		&i.Content,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, username, tag, title, image_url, content, category_id, created_at FROM posts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Tag,
		&i.Title,
		&i.ImageUrl,
		&i.Content,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, username, tag, title, image_url, content, category_id, created_at FROM posts
WHERE username = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListPostsParams struct {
	Username string `json:"username"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, arg.Username, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Tag,
			&i.Title,
			&i.ImageUrl,
			&i.Content,
			&i.CategoryID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET 
  tag = $2,
  title = $3,
  image_url = $4,
  content = $5,
  category_id = $6
WHERE id = $1
RETURNING id, username, tag, title, image_url, content, category_id, created_at
`

type UpdatePostParams struct {
	ID         int64  `json:"id"`
	Tag        string `json:"tag"`
	Title      string `json:"title"`
	ImageUrl   string `json:"image_url"`
	Content    string `json:"content"`
	CategoryID string `json:"category_id"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePost,
		arg.ID,
		arg.Tag,
		arg.Title,
		arg.ImageUrl,
		arg.Content,
		arg.CategoryID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Tag,
		&i.Title,
		&i.ImageUrl,
		&i.Content,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}
