// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: role.sql

package db

import (
	"context"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
  role_name
) VALUES (
  $1
) RETURNING id, role_name, created_at
`

func (q *Queries) CreateRole(ctx context.Context, roleName string) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole, roleName)
	var i Role
	err := row.Scan(&i.ID, &i.RoleName, &i.CreatedAt)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, role_name, created_at FROM roles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRole(ctx context.Context, id int64) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRole, id)
	var i Role
	err := row.Scan(&i.ID, &i.RoleName, &i.CreatedAt)
	return i, err
}
